"""Generate the missing implementation-details appendix (review fix #8).

The review flagged that the paper never specifies: what the semantic signal
actually is (it is hidden-state cosine similarity — there is NO external
embedding model), the shortlist expansion factor, the segment risk mixture,
the KCD preservation constants, or the codec hyperparameters. This script
emits a LaTeX appendix table whose values are transcribed from the code
constants in paper2_memory/policies.py, paper3_codec/policies.py, and
paper3_codec/run_paper3.py, with file references so reviewers can audit.

    python june_fixes/manuscript/implementation_details_appendix.py
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATHS = [
    REPO_ROOT / "june_fixes" / "manuscript" / "generated" / "table_implementation_details.tex",
    REPO_ROOT / "ACL_manuscript" / "generated" / "table_implementation_details.tex",
]

ROWS = [
    # (parameter, value, source)
    (r"Semantic signal", r"cosine similarity between turn hidden states and the target-turn hidden state (no external embedding model)", r"paper2\_memory/policies.py:turn\_semantic\_risk"),
    (r"Hidden-state summary", r"last-token hidden state of the final layer (\texttt{state\_layer}$=-1$)", r"paper1\_geometry/modeling.py"),
    (r"Turn token cost", r"tokenized chat-template length deltas, floor 1", r"paper3\_codec/run\_paper3.py:\_prefix\_turn\_costs"),
    (r"Recent window (always kept)", r"2 turns", r"study defaults"),
    (r"Minimum history before evaluation", r"4 turns", r"study defaults"),
    (r"Max input tokens", r"768 (policy studies), 1024 (QA generation)", r"study defaults"),
    (r"Segment span (KCD)", r"2 (hard set), 3 (support-aware variants), budget-aware for semantic KCD", r"paper3\_codec/run\_paper3.py"),
    (r"Segment risk score", r"$0.65\cdot\mathrm{mean} + 0.35\cdot\max$ of turn risks", r"paper3\_codec/policies.py:\_segment\_score"),
    (r"Support-score mixing", r"risk $+\,0.85\cdot$support (priority); risk $+\,0.60$--$0.75\cdot$support (segment values)", r"paper3\_codec/policies.py"),
    (r"Compress preservation factor", r"$0.86 + 0.12\,(1-\text{compression ratio})$", r"paper3\_codec/policies.py"),
    (r"Object-type preservation priors", r"constraint 0.92, update 0.89, event 0.88, persona 0.87, generic 0.84", r"paper3\_codec/policies.py"),
    (r"Semantic shortlist budget", r"$2.0\times$ the token budget (expansion factor), latest user turn force-included", r"paper3\_codec/policies.py:semantic\_shortlist\_mask"),
    (r"Budget allocation", r"value-density greedy (turn policies); exact DP over keep/compress/evict (KCD)", r"paper2\_memory/policies.py, paper3\_codec/policies.py"),
    (r"Target-turn sampling", r"stride 4, max 16 target turns per conversation (scale-up runs)", r"scale-up runners"),
    (r"Significance testing", r"paired sign-flip permutation test (4000 resamples), bootstrap CIs (2000 resamples), row and conversation level", r"paper3\_codec/stats.py"),
    (r"Decoding (QA accuracy)", r"greedy, max 64 new tokens", r"june\_fixes/qa\_accuracy"),
    (r"Hardware envelope", r"compact open-weight models, fp16 on CUDA, batch size via \texttt{EXTRACT\_BATCH\_SIZE}", r"paper1\_geometry/modeling.py"),
]


def main() -> None:
    lines = [
        r"% Auto-generated by june_fixes/manuscript/implementation_details_appendix.py",
        r"% Do not edit by hand; values are transcribed from code constants.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Implementation details for all policies and studies. Source files refer to the released code.}",
        r"\label{tab:implementation_details}",
        r"\small",
        r"\begin{tabular}{p{0.24\textwidth}p{0.45\textwidth}p{0.24\textwidth}}",
        r"\toprule",
        r"Parameter & Value & Source \\",
        r"\midrule",
    ]
    for parameter, value, source in ROWS:
        lines.append(f"{parameter} & {value} & \\texttt{{{source}}} \\\\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
        "",
    ]
    content = "\n".join(lines)
    for path in OUTPUT_PATHS:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"[implementation_details] wrote {path}")


if __name__ == "__main__":
    main()
